In [3]:
wards = pd.read_csv(
r"C:\Users\chait\OneDrive\Desktop\heat_model\data\chennai_wards.csv",
encoding="latin1",
on_bad_lines="skip"
)

wards.head()

     <!DOCTYPE html><html lang="en-GB"><head><script nonce="l/87a6WRpvhIYcsdeahtmA">var DOCS_timing={}; DOCS_timing['pls']=new Date().getTime();</script><meta property="og:title" content="Open City - Chennai Streets-All-stripped"><meta property="og:type" content="article"><meta property="og:site_name" content="Google Docs"><meta property="og:url" content="https://docs.google.com/spreadsheets/d/1SqVb2rshMPXMoCWYwJqcO0yV6VRD2GQ_J65WiC3jEyM/edit?usp=sharing&amp;usp=embed_facebook"><meta property="og:image" content="https://lh6.googleusercontent.com/EQp0CymZEbfLm4kd26DfjkdK8wV5cdh3ofQtG5UerAdTF7XS9cOEuNG0mU3IPNAJPYCZnnm9Om1J2A=w1200-h630-p"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:description" content="All
Ward                                        Street Name
1                                ENNORE KUPPAM 1 STREET
1                                ENNORE KUPPAM 2 STREET
1                                ENNORE KUPPAM 3 STREET
1                                ENNORE KUPPAM 4 STREET

In [4]:
wards.columns

Index(['<!DOCTYPE html><html lang="en-GB"><head><script nonce="l/87a6WRpvhIYcsdeahtmA">var DOCS_timing={}; DOCS_timing['pls']=new Date().getTime();</script><meta property="og:title" content="Open City - Chennai Streets-All-stripped"><meta property="og:type" content="article"><meta property="og:site_name" content="Google Docs"><meta property="og:url" content="https://docs.google.com/spreadsheets/d/1SqVb2rshMPXMoCWYwJqcO0yV6VRD2GQ_J65WiC3jEyM/edit?usp=sharing&amp;usp=embed_facebook"><meta property="og:image" content="https://lh6.googleusercontent.com/EQp0CymZEbfLm4kd26DfjkdK8wV5cdh3ofQtG5UerAdTF7XS9cOEuNG0mU3IPNAJPYCZnnm9Om1J2A=w1200-h630-p"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:description" content="All'], dtype='object')

In [9]:
pip install geopandas

Requirement already satisfied: geopandas in c:\users\chait\anaconda3\lib\site-packages (1.1.3)
Requirement already satisfied: numpy>=1.24 in c:\users\chait\anaconda3\lib\site-packages (from geopandas) (1.26.4)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\chait\anaconda3\lib\site-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in c:\users\chait\anaconda3\lib\site-packages (from geopandas) (24.1)
Requirement already satisfied: pandas>=2.0.0 in c:\users\chait\anaconda3\lib\site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\chait\anaconda3\lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\chait\anaconda3\lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\chait\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\chait\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\chait\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2023.3)
Requirement already satisfied: certifi in c:\users\chait\anaconda3\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2025.4.26)
Requirement already satisfied: six>=1.5 in c:\users\chait\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
weather = pd.read_csv(
r"C:\Users\chait\OneDrive\Desktop\heat_model\data\climate_data.csv"
)

weather.head()

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
0,Delhi,2000-01-01,19.9,7.4,19.2,5.8,0.0,0.0,0,10.9,13.3,58
1,Delhi,2000-01-02,20.0,5.5,18.9,3.4,0.0,0.0,3,9.5,14.8,326
2,Delhi,2000-01-03,20.1,6.3,18.2,4.3,0.0,0.0,0,10.0,23.8,309
3,Delhi,2000-01-04,19.8,6.4,18.5,4.2,0.0,0.0,0,8.6,18.7,311
4,Delhi,2000-01-05,19.4,5.3,17.7,3.2,0.0,0.0,0,9.4,20.2,322

In [3]:
chennai_weather = weather[weather["city"] == "Chennai"]

chennai_weather.head()

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
27396,Chennai,2000-01-01,27.1,22.6,28.1,23.2,0.0,0.0,2,22.4,38.9,51
27397,Chennai,2000-01-02,27.3,21.9,27.8,23.0,0.0,0.0,3,19.9,34.9,33
27398,Chennai,2000-01-03,26.8,21.5,27.2,22.4,0.0,0.0,3,22.9,40.0,35
27399,Chennai,2000-01-04,27.1,20.8,28.2,22.1,0.0,0.0,3,20.4,36.7,32
27400,Chennai,2000-01-05,27.0,22.7,28.3,24.3,0.3,0.3,51,24.2,42.1,29

In [14]:
import os

os.listdir(r"C:\Users\chait\OneDrive\Desktop\heat_model\data")

['climate_data.csv', 'Wards.geojson.txt']

In [15]:
import geopandas as gpd

wards = gpd.read_file(
r"C:\Users\chait\OneDrive\Desktop\heat_model\data\Wards.geojson"
)

wards.head()

,Zone_No,Ward_No,Zone_Name,AREA,PERIMETER,geometry
0,IX,119,TEYNAMPET,0.000115,0.061956,"POLYGON ((80.2709 13.04753, 80.27062 13.04759,..."
1,I,7,THIRUVOTTIYUR,0.000645,0.124303,"POLYGON ((80.29467 13.15558, 80.29291 13.15137..."
2,III,26,MADHAVARAM,0.000401,0.096859,"POLYGON ((80.22978 13.14719, 80.22842 13.14495..."
3,XIII,174,ADYAR,0.000695,0.121556,"POLYGON ((80.24043 13.00684, 80.2413 13.00659,..."
4,X,132,KODAMBAKKAM,0.000117,0.051055,"POLYGON ((80.20803 13.03565, 80.20835 13.03708..."

In [17]:
wards.columns

Index(['Zone_No', 'Ward_No', 'Zone_Name', 'AREA', 'PERIMETER', 'geometry'], dtype='object')

In [18]:
areas = wards["Ward_No"].tolist()

areas[:10]

[119, 7, 26, 174, 132, 37, 70, 101, 60, 16]

In [19]:
import pandas as pd

weather = pd.read_csv(
r"C:\Users\chait\OneDrive\Desktop\heat_model\data\climate_data.csv"
)

weather.head()

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
0,Delhi,2000-01-01,19.9,7.4,19.2,5.8,0.0,0.0,0,10.9,13.3,58
1,Delhi,2000-01-02,20.0,5.5,18.9,3.4,0.0,0.0,3,9.5,14.8,326
2,Delhi,2000-01-03,20.1,6.3,18.2,4.3,0.0,0.0,0,10.0,23.8,309
3,Delhi,2000-01-04,19.8,6.4,18.5,4.2,0.0,0.0,0,8.6,18.7,311
4,Delhi,2000-01-05,19.4,5.3,17.7,3.2,0.0,0.0,0,9.4,20.2,322

In [20]:
chennai_weather = weather[weather["city"] == "Chennai"]

chennai_weather.head()

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
27396,Chennai,2000-01-01,27.1,22.6,28.1,23.2,0.0,0.0,2,22.4,38.9,51
27397,Chennai,2000-01-02,27.3,21.9,27.8,23.0,0.0,0.0,3,19.9,34.9,33
27398,Chennai,2000-01-03,26.8,21.5,27.2,22.4,0.0,0.0,3,22.9,40.0,35
27399,Chennai,2000-01-04,27.1,20.8,28.2,22.1,0.0,0.0,3,20.4,36.7,32
27400,Chennai,2000-01-05,27.0,22.7,28.3,24.3,0.3,0.3,51,24.2,42.1,29

In [21]:
import numpy as np

chennai_weather["ward"] = np.random.choice(areas, len(chennai_weather))

C:\Users\chait\AppData\Local\Temp\ipykernel_5916\2351800720.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chennai_weather["ward"] = np.random.choice(areas, len(chennai_weather))

In [22]:
import numpy as np

chennai_weather.loc[:, "ward"] = np.random.choice(areas, len(chennai_weather))

In [23]:
chennai_weather = weather[weather["city"] == "Chennai"]

In [24]:
chennai_weather.head()

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
27396,Chennai,2000-01-01,27.1,22.6,28.1,23.2,0.0,0.0,2,22.4,38.9,51
27397,Chennai,2000-01-02,27.3,21.9,27.8,23.0,0.0,0.0,3,19.9,34.9,33
27398,Chennai,2000-01-03,26.8,21.5,27.2,22.4,0.0,0.0,3,22.9,40.0,35
27399,Chennai,2000-01-04,27.1,20.8,28.2,22.1,0.0,0.0,3,20.4,36.7,32
27400,Chennai,2000-01-05,27.0,22.7,28.3,24.3,0.3,0.3,51,24.2,42.1,29

In [25]:
final_data = chennai_weather[[
"city",
"ward",
"date",
"temperature_2m_max",
"temperature_2m_min",
"precipitation_sum",
"wind_speed_10m_max"
]]

KeyError: "['ward'] not in index"

In [26]:
chennai_weather.columns

Index(['city', 'date', 'temperature_2m_max', 'temperature_2m_min',
       'apparent_temperature_max', 'apparent_temperature_min',
       'precipitation_sum', 'rain_sum', 'weather_code', 'wind_speed_10m_max',
       'wind_gusts_10m_max', 'wind_direction_10m_dominant'],
      dtype='object')

In [27]:
import numpy as np

chennai_weather.loc[:, "ward"] = np.random.choice(areas, len(chennai_weather))

C:\Users\chait\AppData\Local\Temp\ipykernel_5916\3422387411.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chennai_weather.loc[:, "ward"] = np.random.choice(areas, len(chennai_weather))

In [28]:
chennai_weather = weather[weather["city"] == "Chennai"].copy()

In [29]:
import numpy as np

chennai_weather["ward"] = np.random.choice(areas, len(chennai_weather))

In [30]:
chennai_weather.head()

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,ward
27396,Chennai,2000-01-01,27.1,22.6,28.1,23.2,0.0,0.0,2,22.4,38.9,51,121
27397,Chennai,2000-01-02,27.3,21.9,27.8,23.0,0.0,0.0,3,19.9,34.9,33,56
27398,Chennai,2000-01-03,26.8,21.5,27.2,22.4,0.0,0.0,3,22.9,40.0,35,16
27399,Chennai,2000-01-04,27.1,20.8,28.2,22.1,0.0,0.0,3,20.4,36.7,32,21
27400,Chennai,2000-01-05,27.0,22.7,28.3,24.3,0.3,0.3,51,24.2,42.1,29,182

In [31]:
final_data = chennai_weather[
[
"city",
"ward",
"date",
"temperature_2m_max",
"temperature_2m_min",
"precipitation_sum",
"wind_speed_10m_max"
]
]

In [32]:
final_data.head()

,city,ward,date,temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max
27396,Chennai,121,2000-01-01,27.1,22.6,0.0,22.4
27397,Chennai,56,2000-01-02,27.3,21.9,0.0,19.9
27398,Chennai,16,2000-01-03,26.8,21.5,0.0,22.9
27399,Chennai,21,2000-01-04,27.1,20.8,0.0,20.4
27400,Chennai,182,2000-01-05,27.0,22.7,0.3,24.2

In [33]:
final_data.to_csv(
r"C:\Users\chait\OneDrive\Desktop\heat_model\data\chennai_heat_dataset.csv",
index=False
)

#model train below steps

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

import pickle

In [5]:
import pandas
import numpy
import sklearn
import pickle

print("All libraries are installed successfully")

All libraries are installed successfully

In [8]:

df = pd.read_csv(r"C:\Users\chait\OneDrive\Desktop\heat_model\data\chennai_heat_dataset.csv")

df.head()

,city,ward,date,temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max
0,Chennai,121,2000-01-01,27.1,22.6,0.0,22.4
1,Chennai,56,2000-01-02,27.3,21.9,0.0,19.9
2,Chennai,16,2000-01-03,26.8,21.5,0.0,22.9
3,Chennai,21,2000-01-04,27.1,20.8,0.0,20.4
4,Chennai,182,2000-01-05,27.0,22.7,0.3,24.2

In [9]:
df.columns

Index(['city', 'ward', 'date', 'temperature_2m_max', 'temperature_2m_min',
       'precipitation_sum', 'wind_speed_10m_max'],
      dtype='object')

In [11]:
def heat_risk(temp):

    if temp < 30:
        return "Low"

    elif temp < 35:
        return "Medium"

    else:
        return "High"


df["heat_risk"] = df["temperature_2m_max"].apply(heat_risk)

In [12]:
df.head()

,city,ward,date,temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max,heat_risk
0,Chennai,121,2000-01-01,27.1,22.6,0.0,22.4,Low
1,Chennai,56,2000-01-02,27.3,21.9,0.0,19.9,Low
2,Chennai,16,2000-01-03,26.8,21.5,0.0,22.9,Low
3,Chennai,21,2000-01-04,27.1,20.8,0.0,20.4,Low
4,Chennai,182,2000-01-05,27.0,22.7,0.3,24.2,Low

In [13]:
X = df[[
    "temperature_2m_max",
    "temperature_2m_min",
    "precipitation_sum",
    "wind_speed_10m_max"
]]

y = df["heat_risk"]

In [15]:
df["heat_risk"] = df["heat_risk"].map({
    "Low": 0,
    "Medium": 1,
    "High": 2
})

In [16]:
df.head()

,city,ward,date,temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max,heat_risk
0,Chennai,121,2000-01-01,27.1,22.6,0.0,22.4,0
1,Chennai,56,2000-01-02,27.3,21.9,0.0,19.9,0
2,Chennai,16,2000-01-03,26.8,21.5,0.0,22.9,0
3,Chennai,21,2000-01-04,27.1,20.8,0.0,20.4,0
4,Chennai,182,2000-01-05,27.0,22.7,0.3,24.2,0

In [17]:
X = df[
    [
        "temperature_2m_max",
        "temperature_2m_min",
        "precipitation_sum",
        "wind_speed_10m_max"
    ]
]

y = df["heat_risk"]

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [19]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

In [20]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [21]:
predictions = model.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, predictions))

Accuracy: 1.0

In [23]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       660
           1       1.00      1.00      1.00       843
           2       1.00      1.00      1.00       324

    accuracy                           1.00      1827
   macro avg       1.00      1.00      1.00      1827
weighted avg       1.00      1.00      1.00      1827

In [28]:
import os
import pickle

os.makedirs("models", exist_ok=True)

pickle.dump(model, open("models/heat_model.pkl", "wb"))

In [29]:
import os
os.getcwd()

'C:\\Users\\chait'

In [30]:
import os
os.makedirs("models", exist_ok=True)

In [31]:
import pickle

with open("models/heat_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully!")

Model saved successfully!

In [32]:
os.listdir("models")

['heat_model.pkl']

In [33]:
import pickle

pickle.dump(model, open("models/heat_model.pkl", "wb"))

In [34]:
import os
os.getcwd()

'C:\\Users\\chait'

In [35]:
import os

os.chdir(r"C:\Users\chait\OneDrive\Desktop\heat_model")

print(os.getcwd())

C:\Users\chait\OneDrive\Desktop\heat_model

In [36]:
import pickle

with open("models/heat_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully")

Model saved successfully

In [37]:
model.predict([[36, 30, 0, 15]])

C:\Users\chait\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([2], dtype=int64)

In [40]:
import pandas as pd

sample = pd.DataFrame([[36,30,0,15]], columns=[
    "temperature_2m_max",
    "temperature_2m_min",
    "precipitation_sum",
    "wind_speed_10m_max"
])

model.predict(sample)

array([2], dtype=int64)

In [41]:
prediction = model.predict(sample)[0]

labels = {
    0: "Low",
    1: "Medium",
    2: "High"
}

print("Heat Risk:", labels[prediction])

Heat Risk: High

In [42]:
sample = pd.DataFrame([[28,24,5,10]], columns=[
    "temperature_2m_max",
    "temperature_2m_min",
    "precipitation_sum",
    "wind_speed_10m_max"
])

In [43]:
sample = pd.DataFrame([[33,27,0,12]], columns=[
    "temperature_2m_max",
    "temperature_2m_min",
    "precipitation_sum",
    "wind_speed_10m_max"
])

In [44]:
sample = pd.DataFrame([[38,30,0,8]], columns=[
    "temperature_2m_max",
    "temperature_2m_min",
    "precipitation_sum",
    "wind_speed_10m_max"
])

In [45]:
prediction = model.predict(sample)[0]

labels = {
    0: "Low",
    1: "Medium",
    2: "High"
}

print("Heat Risk:", labels[prediction])

Heat Risk: High

In [46]:
import pandas as pd

sample = pd.DataFrame([[36,30,0,15]], columns=[
    "temperature_2m_max",
    "temperature_2m_min",
    "precipitation_sum",
    "wind_speed_10m_max"
])

prediction = model.predict(sample)[0]

labels = {
    0: "Low",
    1: "Medium",
    2: "High"
}

print("Heat Risk:", labels[prediction])

Heat Risk: High

In [3]:
import requests

url = "http://127.0.0.1:5000/predict_heat"

data = {
    "temperature_2m_max": 36,
    "temperature_2m_min": 30,
    "precipitation_sum": 0,
    "wind_speed_10m_max": 15
}

response = requests.post(url, json=data)

print("Status:", response.status_code)
print("Result:", response.json())

Status: 200
Result: {'heat_risk': 'High'}

In [2]:
import requests

url = "http://127.0.0.1:5000/predict_heat"

data = {
    "temperature_2m_max": 36,
    "temperature_2m_min": 30,
    "precipitation_sum": 0,
    "wind_speed_10m_max": 15
}

response = requests.post(url, json=data)

print(response.json())

{'heat_risk': 'High'}